services:
  - type: web
    name: tamayodb-api
    env: node
    rootDir: tamayodb-website/backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000